name: tester
authors:
  - Jonah Williams

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  vm_service: 4.0.4
  package_config: 1.9.3
  uuid: 2.0.4
  args: 1.6.0
  pedantic: 1.9.0
  path: 1.7.0

dev_dependencies:
  test: 1.14.2