name: tester
authors:
  - Jonah Williams

dependencies:
  vm_service: 4.0.0
  file:
  process:
  platform:
  package_config:
  uuid: 2.0.4
  args: 1.6.0

dev_dependencies:
  pedantic: 1.9.0
  test: 1.14.2