name: expect
description: A tiny expectation library for writing tests based on matcher and test.
version: 0.0.3
repository: https://github.com/jonahwilliams/tester

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  matcher: ^0.12.12
