name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Build
        run: dart2native -o tester bin/tester.dart
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: tester
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_windows:
    runs-on: windows-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Build
        run: dart2native -o tester.exe bin/tester.dart
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: tester.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_macos:
    runs-on: macos-latest
    container:
      image:  google/dart:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pub get
      - name: Build
        run: dart2native -o tester bin/tester.dart
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: tester
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
